###################################|###|####################################
#   _____                          |   |                                   #
#  |  __ \--.--.----.-----.-----.  |===|  This file is part of Byron, an   #
#  |  __ <  |  |   _|  _  |     |  |___|  evolutionary source-code fuzzer. #
#  |____/ ___  |__| |_____|__|__|   ).(   Version 0.8a1 "Don Juan"         #
#        |_____|                    \|/                                    #
#################################### ' #####################################
# Copyright 2023-25 Giovanni Squillero and Alberto Tonda
# SPDX-License-Identifier: Apache-2.0

[project]
    name = "byron"
    version = "0.8a1.dev66"
    description = "An evolutionary source-code fuzzer"
    authors = [
        { name = "Giovanni Squillero", email = "giovanni.squillero@polito.it" },
        { name = "Alberto Tonda", email = "alberto.tonda@inrae.fr" },
    ]
    readme = "README.md"
    requires-python = ">=3.10,<4.0"

[tool.poetry]

    [tool.poetry.dependencies]
        dill       = ">=0.3.7"
        icecream   = "^2.1.3"
        python     = ">=3.10,<4.0"
        rich       = { extras = ["jupyter"], version = "^13.7.1" }
        scipy      = ">=1.10"
        tqdm       = ">=4.66.5"
        networkx    = "^3.4.2"
        numpy       = "^2.2.5"
        joblib      = { version = ">=1.3", optional = true }
        matplotlib  = { version = ">=3.9.1", optional = true }
        psutil      = { version = ">=6.0", optional = true }
        poetry-core = ">=2.0.0,<3.0.0"

    [tool.poetry.extras]
        # Use: poetry install --all-extras
        full      = ["joblib", "matplotlib", "psutil"]
        info      = ["psutil"]
        multitask = ["joblib"]
        plot      = ["matplotlib"]

    [tool.poetry.group.dev.dependencies]
        bumpver      = "^2026.1132"
        coverage     = "^7.6"
        jupyter      = "^1.0.0"
        mypy         = ">=1.11.1"
        pytest-emoji = "^0.2.0"
        ipykernel    = "^7.3.0"
        pytest       = "^9.0.3"
        ruff         = "^0.15.16"

[tool.pytest.ini_options]
    pythonpath     = ["src", "."]
    filterwarnings = ["ignore::DeprecationWarning"]

[tool.coverage.run]
    branch = true

[tool.coverage.report]
    include = ['src/*', 'test/*']
    omit    = ['.*/*', 'venv/*']

[tool.mypy]
    modules                = ['byron']
    ignore_missing_imports = true

[tool.ruff]
    target-version = "py312"
    line-length    = 120
    extend-include = ["*.ipynb"]

    [tool.ruff.lint]
        extend-select = ["I"]

    [tool.ruff.format]
        # Prefer single quotes over double quotes.
        quote-style = "preserve"
        line-ending = "native"

[tool.bumpver]
    current_version = "0.8a1.dev66"
    version_pattern = "MAJOR.MINOR[PYTAGNUM].devINC0"
    commit_message  = "style(bumpver): Bump version to {new_version}"
    commit          = true
    push            = false

    [tool.bumpver.file_patterns]
        "pyproject.toml" = [
            'current_version = "{pep440_version}"',
            'version = "{pep440_version}"$',
        ]
        "docs/index.md" = [" v{pep440_version}"]
        "src/byron/global_symbols.py" = [
            '__date__ = "0D-0M-YYYY"',
            '__version__ = "{pep440_version}"',
        ]

[build-system]
    requires      = ["poetry-core>=2.0.0,<3.0.0"]
    build-backend = "poetry.core.masonry.api"
