name: Run Python tests

on: [push]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.14"]
        include:
          # Test the upcoming Python 3.15 but don't let it block the PR
          - python-version: "3.15-dev"
            experimental: true

    steps:
      # check-out repo and set-up python
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Berlin"
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          # Optional: enables automatic caching of your uv cache directory
          enable-cache: true

      - name: Running PyTest on Python ${{ matrix.python-version }}
        continue-on-error: ${{ matrix.experimental == true }}
        run: |
          uv sync --all-extras
          uv pip pytest